language: node_js
node_js: stable
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 39.105.132.146
install:
- npm install
script:
- npm run build
after_success:
- rsync -az --delete ./dist/* root@39.105.132.146:/data/www/hackthon/
- $pd
before_install:
- openssl aes-256-cbc -K $encrypted_d48e55a32b3e_key -iv $encrypted_d48e55a32b3e_iv
  -in authorized_keys.enc -out ~/.ssh/authorized_keys -d
